- package-lock.json
*Issue #, if available:*
*Description of changes:*
Fixed security vulnerabilities that were reported with npm audit.
Updated outdated dependencies (npm outdated)
Similar to: https://github.com/awslabs/wdio-aws-device-farm-service/pull/3
> Update dependencies to fix security vulnerabilities on `v6`

- .github/workflows/npm-publish.yml
*Description of changes:* Automatically publish to npmjs.com
> Create npm-publish.yml to automatically publish to npmjs.com

- package-lock.json
- package.json
*Description of changes:* Updates version to 7.0.1 with updated dependencies
> Bump version to 7.0.1

- package.json
Bump minor version to 7.0.2 prior to release
> Bump to 7.0.2

- package-lock.json
- package.json
*Description of changes:*
* updating dependencies
> Release version 7.0.3

- .github/PULL_REQUEST_TEMPLATE.md
*Issue #, if available:*
*Description of changes:*
- Adding AWS open source contribution pr template per guidance.
> Add AWS open source contribution pr template

- package-lock.json
- package.json
*Issue #, if available:*
*Description of changes:*
> Release version 7.0.4

- package-lock.json
- package.json
* Security fixes:
* https://github.com/awslabs/wdio-aws-device-farm-service/pull/28 
* https://github.com/awslabs/wdio-aws-device-farm-service/pull/29
* https://github.com/awslabs/wdio-aws-device-farm-service/pull/31
> Releasing 7.0.6

- package-lock.json
- package.json
Signed-off-by: Arnulfo Solis Ramirez <arnsolis@amazon.com>
* https://github.com/awslabs/wdio-aws-device-farm-service/pull/32
> Release v7.0.7

- package-lock.json
- package.json
Signed-off-by: Kamil Bladoszewski <kblado@amazon.de>
* #34 
> Release v7.1.0

- package-lock.json
- package.json
Signed-off-by: Daniil Migachev [daniilmc@amazon.de](mailto:daniilmc@amazon.de)
* https://github.com/awslabs/wdio-aws-device-farm-service/pull/38
> Release v7.1.1

- package-lock.json
- package.json
Signed-off-by: Longfei Wang [longfeiw@amazon.de](mailto:longfeiw@amazon.de)
* https://github.com/awslabs/wdio-aws-device-farm-service/pull/40
> Release v7.1.2

- package-lock.json
- package.json
> Bump to v8.0.1

- README.md
- package.json
update the contributors and readme.md
> update the contributors and readme.md

- package-lock.json
- package.json
Signed-off-by: Kamil Bladoszewski kblado@amazon.com
* #52 
* #53  
> Release v8.0.2

- package-lock.json
- package.json
_Description of changes:_ Updates version to 8.0.4 with updated dependencies
> Bump version to 8.0.4

- package-lock.json
- package.json
> Bump version to 8.0.5

- package-lock.json
- package.json
_Description of changes:_ Bump version to 8.0.7
> Release v8.0.7

- package-lock.json
- package.json
_Description of changes:_ Updates version to 8.0.8 with updated dependencies
> Version release

- package-lock.json
- package.json
> Release v8.0.9

- package-lock.json
- package.json
> Release v8.0.10

- package-lock.json
- package.json
> Release v8.0.11

- package-lock.json
- package.json
> Release 8.0.12

- package-lock.json
- package.json
> Release v8.0.13

- package-lock.json
- package.json
> Release v8.0.14

- package-lock.json
- package.json
> Release 8.0.15
